# Generated by Django 4.2.10 on 2024-03-04 19:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
