# Generated by Django 4.2.10 on 2024-02-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremailactions',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='useremailactions',
            old_name='delete',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='useremailactions',
            old_name='star',
            new_name='starred',
        ),
        migrations.RemoveField(
            model_name='email',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc',
        ),
    ]
