# Generated by Django 4.2.10 on 2024-02-27 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, max_length=16, unique=True),
        ),
    ]
