# Generated by Django 4.2.10 on 2024-02-27 09:16
import uuid

import apps.mail.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mail', '0002_alter_email_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4(), editable=False, max_length=16, unique=True),
        ),
    ]
