# Generated by Django 4.2.10 on 2024-02-29 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_email_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
