# Generated by Django 4.2.10 on 2024-03-01 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0006_alter_email_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_archived_by_recipient',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_archived_by_sender',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_deleted_by_recipient',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_deleted_by_sender',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_starred_by_recipient',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_starred_by_sender',
        ),
        migrations.CreateModel(
            name='UserEmailActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
