# Generated by Django 4.2.10 on 2024-03-01 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0007_alter_email_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEmailActions',
            new_name='UserEmail',
        ),
    ]
