# Generated by Django 4.2.10 on 2024-03-01 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0008_rename_useremailactions_useremail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEmail',
            new_name='UserEmailAction',
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='email',
            name='parent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_parent', to='mail.email'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mail.email'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
