# Generated by Django 4.2.10 on 2024-03-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_alter_email_recipient_alter_email_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['timestamp']},
        ),
    ]
